#!/usr/bin/env ruby

require 'fileutils'
require 'tmpdir'

$library = File.expand_path(File.dirname(__FILE__)) + '/library'
rb3pkg = File.expand_path(File.dirname(__FILE__)) + '/rb3pkg/rb3pkg.exe'

if ARGV.length < 2 || ARGV.include?('--help')
  STDERR.puts "Usage: #{$0} song1 [song2 song3 ...] out_rb3con"
  STDERR.puts "Make a new CON package from a list of songs."
  exit(ARGV.include?('--help') ? 0 : 1)
end

Dir.mktmpdir do |tmp|
  all_dta = ""
  all_dta_upgrades = ""
  ARGV[0..-2].each do |song_name|
    Dir["#{$library}/#{song_name}/*/songs/songs.dta"].each do |f|
      all_dta += "\n" + File.read(f, encoding: Encoding::ISO_8859_1)
    end
    Dir["#{$library}/#{song_name}/*/songs_upgrades/upgrades.dta"].each do |f|
      all_dta_upgrades += "\n" + File.read(f, encoding: Encoding::ISO_8859_1)
    end
    Dir["#{$library}/#{song_name}/*/*"].each do |thing|
      FileUtils.cp_r(thing, tmp)
    end
  end
  File.write("#{tmp}/songs/songs.dta", all_dta) unless all_dta.empty?
  File.write("#{tmp}/songs_upgrades/upgrades.dta", all_dta_upgrades) unless all_dta_upgrades.empty?
  title = ARGV[0]
  if ARGV.length > 2
    title += ' ...'
  end
  system('mono', rb3pkg, '-f', tmp, '-p', title, ARGV[-1])
end
